# Generated by Django 5.2.11 on 2026-02-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('line', 'LINE')], max_length=10)),
                ('contact_detail', models.CharField(help_text='Email, phone number, or LINE ID', max_length=200)),
                ('age_range', models.CharField(choices=[('under_12', 'Under 12'), ('13_17', '13–17'), ('18_25', '18–25'), ('26_40', '26–40'), ('40_plus', '40+')], max_length=10)),
                ('learning_type', models.CharField(choices=[('language', 'Language'), ('culture', 'Culture'), ('wellness', 'Wellness'), ('not_sure', "Not sure yet (I'd like recommendations)")], max_length=20)),
                ('language_english', models.BooleanField(default=False)),
                ('language_mandarin', models.BooleanField(default=False)),
                ('language_french', models.BooleanField(default=False)),
                ('language_korean', models.BooleanField(default=False)),
                ('language_other', models.CharField(blank=True, max_length=100)),
                ('current_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('not_sure', 'Not sure')], max_length=15)),
                ('studied_before', models.BooleanField(help_text='Have you studied this subject/language before?', null=True)),
                ('goal_conversation', models.BooleanField(default=False, verbose_name='Conversation / real-life use')),
                ('goal_school_prep', models.BooleanField(default=False, verbose_name='School or study abroad preparation')),
                ('goal_work', models.BooleanField(default=False, verbose_name='Work / professional use')),
                ('goal_personal', models.BooleanField(default=False, verbose_name='Personal interest/hobby')),
                ('goal_cultural', models.BooleanField(default=False, verbose_name='Cultural experience')),
                ('goal_confidence', models.BooleanField(default=False, verbose_name='Confidence building')),
                ('goal_other', models.CharField(blank=True, max_length=200)),
                ('class_format', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person'), ('either', 'Either is fine')], max_length=10)),
                ('preferred_location', models.CharField(blank=True, choices=[('taipei', 'Taipei'), ('new_york', 'New York'), ('other', 'Other')], max_length=10)),
                ('location_other', models.CharField(blank=True, max_length=100)),
                ('class_type', models.CharField(choices=[('one_on_one', 'One-on-one'), ('small_group', 'Small group')], max_length=15)),
                ('preferred_schedule', models.CharField(choices=[('weekday_day', 'Weekdays (daytime)'), ('weekday_evening', 'Weekdays (evening)'), ('weekends', 'Weekends'), ('flexible', 'Flexible')], max_length=20)),
                ('teacher_style', models.CharField(choices=[('patient', 'Patient & encouraging'), ('conversational', 'Conversational & relaxed'), ('structured', 'Structured & academic'), ('creative', 'Creative & activity-based'), ('not_sure', 'Not sure'), ('other', 'Other')], max_length=20)),
                ('teacher_style_other', models.CharField(blank=True, max_length=200)),
                ('topic_business', models.BooleanField(default=False, verbose_name='Business / Workplace communication')),
                ('topic_technology', models.BooleanField(default=False, verbose_name='Technology / Computer Science')),
                ('topic_music_arts', models.BooleanField(default=False, verbose_name='Music / Arts / Creative fields')),
                ('topic_film_media', models.BooleanField(default=False, verbose_name='Film / Media / Content creation')),
                ('topic_travel', models.BooleanField(default=False, verbose_name='Travel & daily life')),
                ('topic_culture', models.BooleanField(default=False, verbose_name='Culture & social topics')),
                ('topic_academic', models.BooleanField(default=False, verbose_name='Academic subjects')),
                ('topic_exam_prep', models.BooleanField(default=False, verbose_name='Exam preparation')),
                ('topic_casual', models.BooleanField(default=False, verbose_name='Casual conversation')),
                ('topic_other', models.CharField(blank=True, max_length=200)),
                ('specific_topic_interest', models.TextField(blank=True, help_text="Specific topic you'd love to learn or talk about")),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Questionnaire',
                'verbose_name_plural': 'Student Questionnaires',
                'ordering': ['-created_at'],
            },
        ),
    ]
