from django import forms
from .models import StudentQuestionnaire


class StudentQuestionnaireForm(forms.ModelForm):
    class Meta:
        model = StudentQuestionnaire
        fields = [
            'full_name',
            'preferred_contact_method',
            'contact_detail',
            'age_range',
            'learning_type',
            'language_english',
            'language_mandarin',
            'language_french',
            'language_korean',
            'language_other',
            'current_level',
            'studied_before',
            'goal_conversation',
            'goal_school_prep',
            'goal_work',
            'goal_personal',
            'goal_cultural',
            'goal_confidence',
            'goal_other',
            'class_format',
            'preferred_location',
            'location_other',
            'class_type',
            'preferred_schedule',
            'teacher_style',
            'teacher_style_other',
            'topic_business',
            'topic_technology',
            'topic_music_arts',
            'topic_film_media',
            'topic_travel',
            'topic_culture',
            'topic_academic',
            'topic_exam_prep',
            'topic_casual',
            'topic_other',
            'specific_topic_interest',
            'additional_notes',
        ]

        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'preferred_contact_method': forms.RadioSelect(),
            'contact_detail': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Email, phone number, or LINE ID'}),
            'age_range': forms.RadioSelect(),
            'learning_type': forms.RadioSelect(),
            'language_other': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please specify'}),
            'current_level': forms.RadioSelect(),
            'studied_before': forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')]),
            'goal_other': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please specify'}),
            'class_format': forms.RadioSelect(),
            'preferred_location': forms.RadioSelect(),
            'location_other': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please specify'}),
            'class_type': forms.RadioSelect(),
            'preferred_schedule': forms.RadioSelect(),
            'teacher_style': forms.RadioSelect(),
            'teacher_style_other': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please specify'}),
            'topic_other': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Please specify'}),
            'specific_topic_interest': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 3,
                       'placeholder': 'e.g. tech, music, gaming, cooking, startups, K-pop, film, etc.'}),
            'additional_notes': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 4,
                       'placeholder': 'Any additional information you\'d like to share'}),
        }


        labels = {
            'full_name': '1. Full Name',
            'preferred_contact_method': '2. Preferred Contact Method',
            'contact_detail': 'Contact Information',
            'age_range': '3. Age Range',
            'learning_type': '4. What type of learning are you interested in?',
            # Add this section header for question 5
            'language_english': '5. If language, which language(s)? - English',
            'language_mandarin': 'Mandarin Chinese',
            'language_french': 'French',
            'language_korean': 'Korean',
            'language_other': 'Other',
            'current_level': '6. Your current level (if applicable)',
            'studied_before': '7. Have you studied this subject/language before?',
            # Add this section header for question 8
            'goal_conversation': '8. What is your main goal? (Select all that apply) - Conversation / real-life use',
            'goal_school_prep': 'School or study abroad preparation',
            'goal_work': 'Work / professional use',
            'goal_personal': 'Personal interest/hobby',
            'goal_cultural': 'Cultural experience',
            'goal_confidence': 'Confidence building',
            'goal_other': 'Other',
            'class_format': '9. Preferred class format',
            'preferred_location': '10. Preferred location (if in-person)',
            'location_other': 'Other location',
            'class_type': '11. Preferred class type',
            'preferred_schedule': '12. Preferred schedule',
            'teacher_style': '13. Who would you like to learn with?',
            'teacher_style_other': 'Other teaching style',
            # Add this section header for question 14
            'topic_business': '14. Would you like to learn through specific topics or interests? (Select all that apply) - Business / Workplace communication',
            'topic_technology': 'Technology / Computer Science',
            'topic_music_arts': 'Music / Arts / Creative fields',
            'topic_film_media': 'Film / Media / Content creation',
            'topic_travel': 'Travel & daily life',
            'topic_culture': 'Culture & social topics',
            'topic_academic': 'Academic subjects',
            'topic_exam_prep': 'Exam preparation',
            'topic_casual': 'Casual conversation',
            'topic_other': 'Other',
            'specific_topic_interest': "15. Is there a specific topic you'd love to learn or talk about while studying?",
            'additional_notes': '16. Additional notes or requests',
        }